version: '2'
services:
    jhipsterspotlesssample-app:
        image: jhipsterspotlesssample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterspotlesssample-mysql:3306/jhipsterspotlesssample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterspotlesssample-mysql:
        extends:
            file: mysql.yml
            service: jhipsterspotlesssample-mysql
